version: '3.8'

services:
  php:
    build:
      context: ./php/
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html

  apache:
    build:
      context: ./apache/
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    container_name: apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html

  mysql:
    image: mariadb:10.11
    container_name: mysql
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  frontend: {}
  backend: {}

volumes:
  data: {}
